#encoding: utf-8
Band.create(name: 'Macklemore')
Band.create(name: 'Imagine Dragons')
Band.create(name: 'Bruno Mars')
Band.create(name: 'Justin Timberlake')
Band.create(name: 'Rihanna')
Band.create(name: 'Florida Georgia Line')
Band.create(name: 'Taylor Swift')
Band.create(name: 'P!nk')
Band.create(name: 'Drake')
Band.create(name: 'Maroon 5')
Band.create(name: 'Miley Cyrus')
Band.create(name: 'Blake Shelton')
Band.create(name: 'Lil Wayne')
Band.create(name: 'Pitbull')
Band.create(name: 'Calvin Harris')
Band.create(name: 'Robin Thicke')
Band.create(name: 'Luke Bryan')
Band.create(name: 'Katy Perry')
Band.create(name: 'AWOLNATION')
Band.create(name: 'One Direction')
Band.create(name: 'Eminem')
Band.create(name: 'The Lumineers')
Band.create(name: 'Hunter Hayes')
Band.create(name: 'J. Cole')
Band.create(name: 'Phillip Phillips')
Band.create(name: 'Selena Gomez')
Band.create(name: 'Jay-Z')
Band.create(name: 'Zedd')
Band.create(name: 'Tim McGraw')
Band.create(name: 'will.i.am')
Band.create(name: 'Lorde')
Band.create(name: 'Lady Gaga')
Band.create(name: 'Daft Punk')
Band.create(name: 'Anna Kendrick')
Band.create(name: 'Lana Del Rey')
Band.create(name: 'Capital Cities')
Band.create(name: 'Ariana Grande')
Band.create(name: 'Justin Bieber')
Band.create(name: 'Fun.')
Band.create(name: 'Avicii')
Band.create(name: 'Icona Pop')
Band.create(name: 'One Republic')
Band.create(name: 'Ke$ha')
Band.create(name: 'Darius Rucker')
Band.create(name: 'Sage the Gemini')
Band.create(name: 'PSY')
Band.create(name: 'A$AP Rocky')
Band.create(name: 'Demi Lovato')
Band.create(name: 'The Band Perry')
Band.create(name: 'Kendrick Lamar')
Band.create(name: 'Swedish House Mafia')
Band.create(name: 'Carrie Underwood')
Band.create(name: '2 Chainz')
Band.create(name: 'Baauer')
Band.create(name: 'Randy Houser')
Band.create(name: 'Kelly Clarkson')
Band.create(name: 'Jon Henry Odgers')
Band.create(name: 'Fall Out Boy')
Band.create(name: 'Mumford & Sons')
Band.create(name: 'Jason Derülo')
Band.create(name: 'Ciara')
Band.create(name: 'Sara Bareilles')
Band.create(name: 'Passenger')
Band.create(name: 'Lady Antebellum')
Band.create(name: 'Of Monsters and Men')
Band.create(name: 'Lee Brice')
Band.create(name: 'Mariah Carey')
Band.create(name: 'Alicia Keys')
Band.create(name: 'Ellie Goulding')
Band.create(name: 'Miguel')
Band.create(name: 'Thomas Rhett')
Band.create(name: 'Jason Aldean')
Band.create(name: 'Paramore')
Band.create(name: 'Olly Murs')
Band.create(name: 'Wale')
Band.create(name: 'Rocko')
Band.create(name: 'Future')
Band.create(name: 'Miranda Lambert')
Band.create(name: 'The Neighbourhood')
Band.create(name: 'Keith Urban')
Band.create(name: 'Mike WiLL Made It')
Band.create(name: 'Emeli Sandé')
Band.create(name: 'Ed Sheeran')
Band.create(name: 'Ace Hood')
Band.create(name: 'Brad Paisley')
Band.create(name: 'Chris Young')
Band.create(name: 'Brett Eldredge')
Band.create(name: 'The Script')
Band.create(name: 'Kip Moore')
Band.create(name: 'B.o.B')
Band.create(name: 'Zac Brown Band')
Band.create(name: 'Trinidad James')
Band.create(name: 'Kendrick Lamar')
Band.create(name: 'Krewella')
Band.create(name: 'Kenny Chesney')
Band.create(name: 'Tyler Farr')
Band.create(name: 'Eric Church')
Band.create(name: 'Flo Rida')
Band.create(name: 'Avril Lavigne')